basePath: /
host: localhost:8000
info:
  contact:
    email: brunog86@gmail.com
    name: Bruno Gonzaga
    url: http://www.brunogonzaga.dev
  description: Product API with authentication
  license:
    name: MIT
    url: http://mit.com
  termsOfService: http://swagger.io/terms/
  title: Go Expert API de Produtos
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
