POST http://localhost:8000/products HTTP/1.1
Content-Type: : application/json

{
  "name": "Product 1",
  "price": 100
}

###

GET http://localhost:8000/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDgyOTI4NzAsInN1YiI6IjQ4ZjU1OTg5LTNkYTgtNDZhMC04Y2M1LTg1ZmVmMWJjMmI4YiJ9.r1l4m5eUzzVwWYKcu_4dT5HFOWNPc1_g6bp8GjCmFoA

###

GET http://localhost:8000/products/dfe27215-aed8-4649-9b02-24a28caa891e HTTP/1.1
Content-Type: application/json

###

PUT http://localhost:8000/products/dfe27215-aed8-4649-9b02-24a28caa891e HTTP/1.1
Content-Type: application/json

{
  "name": "Product Updated",
  "price": 200
}

###

DELETE http://localhost:8000/products/dfe27215-aed8-4649-9b02-24a28caa891e HTTP/1.1